### ISSUE TITLE
Can't change alpha on `CameraPreview`

### ISSUE THREAD

**Issue by Myzel394** [ujizin/Camposer#27] opened 2023-08-12 17:19 UTC
**please complete the following information**

- Device: Xiaomi Mi 9T Pro and Google Pixel 7 Pro
- Android version: 12 and 13
- Library version: 0.1.0

**Describe the bug**

I'm not able to make the preview transparent.

**To Reproduce**

```kotlin
        CameraPreview(
            modifier = Modifier
                .alpha(0.1f),
            cameraState = cameraState,
            camSelector = camSelector,
        ) {
            // Camera Preview UI
        }
```

**Expected behavior**

Content should be transparent

**Screenshots**

**Are you willing to provide a PR?**

**Comment by Myzel394** [comment] 2023-08-12 17:38
Workaround: Add a box after it and add a transparent background:

```kotlin
CameraPreview(
    modifier = Modifier
        .alpha(0.1f),
    cameraState = cameraState,
    camSelector = camSelector,
) {
    // Camera Preview UI
}
Box(
    modifier = Modifier.background(MaterialTheme.colorScheme.surface.copy(alpha = 0.9f))
)
```

**Comment by ujizin** [comment] 2023-08-15 13:50
Hey @Myzel394, thanks for opening the issue!

Oh... that's rather awkward. I'll investigate the cause of this issue and endeavor to respond ASAP.

**Comment by ujizin** [comment] 2024-01-23 23:46
Hi Myzel, I apologize for the delay! 

It appears that there are some limitations on interoperability with the Modifier alpha when using AndroidView with PreviewView. However, as you mentioned, the workaround seems to be effective. 

Another approach involves wrapping the content parameter from the CameraPreview composable:

```Kotlin
CameraPreview(
    modifier = Modifier
        .alpha(0.1f),
    cameraState = cameraState,
    camSelector = camSelector,
) {
    Box(
        modifier = Modifier.background(MaterialTheme.colorScheme.surface.copy(alpha = 0.9f))
    ) {
         // Camera Preview UI
    }
}
```

Given this info, I won't fix this since it doesn't seem to be related to the Compose library.  I hope this approach is sufficient for you. 

Thanks once again for opening the issue!

**Closed by ujizin** 2024-01-23 23:46 UTC
Labels: bug
